### ISSUE TITLE
数据库表

### ISSUE THREAD

**Issue by q6990774** [snowlyg/IrisAdminApi#1]
hello 我想运行一下，默认里面的是mysql，可是没有数据库的表文件， mysql的数据表能发一份吗？

**Comment by llllash** [comment]
+1 mysql的数据库配置也少了ip和host的配置声明

**Comment by llllash** [comment]
> hello 我想运行一下，默认里面的是mysql，可是没有数据库的表文件， mysql的数据表能发一份吗？

会自动创建表文件啊，只不过连接数据库需要加一下那个连接数据库的ip和port

**Comment by snowlyg** [comment]
@q6990774 数据表会自动创建的，需要在配置文件里面配置好数据库的设置
