### ISSUE TITLE
登录管理员账号报错

### ISSUE THREAD

**Issue by yangkecapf** [snowlyg/IrisAdminApi#17]
重复初始化权限
重复初始化角色
重复初始化账号
Now listening on: http://0.0.0.0:8081
Application started. Press CTRL+C to shut down.
[HTTP Server] http: panic serving [::1]:5203: reflect: call of reflect.Value.Interface on zero Value
![image](https://user-images.githubusercontent.com/15521436/72200692-71a3a200-3487-11ea-90f7-1cc3d297c77c.png)

**Comment by snowlyg** [comment]
![image](https://user-images.githubusercontent.com/45998760/72201947-e0d3c300-3494-11ea-9064-9c0351065e4a.png)
这个包的版本太低了，更新一下
