### ISSUE TITLE
/v1/admin/users/5 Forbidden

### ISSUE THREAD

**Issue by sweetsky0901** [snowlyg/IrisAdminApi#21]
其他的接口都正常，就{id,uint}这种接口都报Forbidden，求问要怎么调试？

**Comment by snowlyg** [comment]
没有权限吧！最好帖一下代码还有报错截图上来！

**Comment by sweetsky0901** [comment]
读代码发现是在这里
![image](https://user-images.githubusercontent.com/32288640/75970389-395e9400-5f0b-11ea-9c8b-3320dbf9ba73.png)

**Comment by snowlyg** [comment]
@sweetsky0901  判断权限的，就是你当前账号没有对应接口的权限，错误码403 禁止访问

**Comment by snowlyg** [comment]
@sweetsky0901  你加群在群里问吧，方便一点！这个问题我关了！

**Comment by sweetsky0901** [comment]
但是我看了表里的数据，是应该有权限的，在casbin_rule里
用户对应的role和role对应的url
