### ISSUE TITLE
如何生成类似图片的权限表？

### ISSUE THREAD

**Issue by glepnir** [snowlyg/IrisAdminApi#23]
@snowlyg 你好。看了下你的文章生成的权限表是这样的。 但是casbin默认生成的都是`v0 v1 v2 v3` 这样的。这个是如何做的？
![image](https://user-images.githubusercontent.com/41671631/90037385-bc73e980-dcf6-11ea-984d-d0c5b83bc290.png)

**Comment by glepnir** [comment]
跑了一下。也是一样的。。

**Comment by snowlyg** [comment]
@glepnir 你好，casbin 生成的表是一个规则表，用来确定其他表的数据关系！算是一个中间表！

**Comment by glepnir** [comment]
并不是。我看了gin-admin 没有casbin_rule. 这个是可以做权限表的。

**Comment by snowlyg** [comment]
@glepnir 项目地址给我看下，或者你截几张数据库的图上来。看看是怎么实现的。

**Comment by glepnir** [comment]
https://github.com/LyricTian/gin-admin   
![image](https://user-images.githubusercontent.com/41671631/90096394-b5d08b00-dd65-11ea-9f77-236bad2a3bdf.png)

**Comment by glepnir** [comment]
我搜了下以为是可以配置的。看来是作者重写的。

**Comment by snowlyg** [comment]
@glepnir 是的作者自己写了适配器

**Comment by glepnir** [comment]
嗯 不纠结了 我去研究下他的code。
