### ISSUE TITLE
gowatch 后出现问题

### ISSUE THREAD

**Issue by LuciferJun1227** [snowlyg/IrisAdminApi#3]
2019/03/14 11:17:44 gowatch.go:111: [INFO] Start building...
2019/03/14 11:17:45 gowatch.go:136: [INFO] Build was successful
2019/03/14 11:17:45 gowatch.go:161: [INFO] Restarting ./IrisApiProject ...
2019/03/14 11:17:45 gowatch.go:173: [INFO] ./IrisApiProject is running...
panic: interface conversion: interface {} is nil, not string

goroutine 1 [running]:
IrisApiProject/database.New(0x433d445)
	/Users/lucifer/Projects/Go/src/IrisApiProject/database/database.go:37 +0x5ed
IrisApiProject/database.init.ializers()
	/Users/lucifer/Projects/Go/src/IrisApiProject/database/database.go:15 +0x22

**Comment by snowlyg** [comment]
看看有没有配置数据库
