### ISSUE TITLE
api文档没有

### ISSUE THREAD

**Issue by LuciferJun1227** [snowlyg/IrisAdminApi#4]
api文档是自动生成的还是本来需要有index.html才行呢

**Comment by snowlyg** [comment]
@LuciferJun1227 自动生成的，要注意 gowatch 时候的权限。

**Comment by LuciferJun1227** [comment]
大佬，用sudo gowatch跑，反而出现问题了，我是不是缺什么重要的东西啊

main.go:4:2: cannot find package "IrisApiProject/config" in any of:
	/usr/local/go/src/IrisApiProject/config (from $GOROOT)
	/Users/lucifer/go/src/IrisApiProject/config (from $GOPATH)
main.go:5:2: cannot find package "IrisApiProject/controllers" in any of:
	/usr/local/go/src/IrisApiProject/controllers (from $GOROOT)
	/Users/lucifer/go/src/IrisApiProject/controllers (from $GOPATH)
main.go:6:2: cannot find package "IrisApiProject/database" in any of:
	/usr/local/go/src/IrisApiProject/database (from $GOROOT)
	/Users/lucifer/go/src/IrisApiProject/database (from $GOPATH)
main.go:7:2: cannot find package "IrisApiProject/middleware" in any of:
	/usr/local/go/src/IrisApiProject/middleware (from $GOROOT)
	/Users/lucifer/go/src/IrisApiProject/middleware (from $GOPATH)
main.go:8:2: cannot find package "IrisApiProject/models" in any of:
	/usr/local/go/src/IrisApiProject/models (from $GOROOT)
	/Users/lucifer/go/src/IrisApiProject/models (from $GOPATH)
main.go:9:2: cannot find package "github.com/betacraft/yaag/yaag" in any of:
	/usr/local/go/src/github.com/betacraft/yaag/yaag (from $GOROOT)
	/Users/lucifer/go/src/github.com/betacraft/yaag/yaag (from $GOPATH)
main.go:10:2: cannot find package "github.com/iris-contrib/middleware/cors" in any of:
	/usr/local/go/src/github.com/iris-contrib/middleware/cors (from $GOROOT)
	/Users/lucifer/go/src/github.com/iris-contrib/middleware/cors (from $GOPATH)
main.go:11:2: cannot find package "github.com/kataras/iris" in any of:
	/usr/local/go/src/github.com/kataras/iris (from $GOROOT)
	/Users/lucifer/go/src/github.com/kataras/iris (from $GOPATH)
main.go:12:2: cannot find package "github.com/kataras/iris/core/router" in any of:
	/usr/local/go/src/github.com/kataras/iris/core/router (from $GOROOT)
	/Users/lucifer/go/src/github.com/kataras/iris/core/router (from $GOPATH)
main.go:13:2: cannot find package "github.com/kataras/iris/middleware/logger" in any of:
	/usr/local/go/src/github.com/kataras/iris/middleware/logger (from $GOROOT)
	/Users/lucifer/go/src/github.com/kataras/iris/middleware/logger (from $GOPATH)
2019/03/14 14:31:28 gowatch.go:133: [ERROR] ============== Build failed ===================

**Comment by snowlyg** [comment]
@LuciferJun1227  你的 go 环境有没有设置好，还有就是检查下所有包是不是都下载好了。

**Comment by uniteweiwei** [comment]
`unitedeMacBook-Pro# go run main.go
main.go:4:2: cannot find package "IrisApiProject/config" in any of:
	/usr/local/go/src/IrisApiProject/config (from $GOROOT)
	/Users/unitexiaowei/goProjects/src/IrisApiProject/config (from $GOPATH)
main.go:5:2: cannot find package "IrisApiProject/controllers" in any of:
	/usr/local/go/src/IrisApiProject/controllers (from $GOROOT)
	/Users/unitexiaowei/goProjects/src/IrisApiProject/controllers (from $GOPATH)
main.go:6:2: cannot find package "IrisApiProject/database" in any of:
	/usr/local/go/src/IrisApiProject/database (from $GOROOT)
	/Users/unitexiaowei/goProjects/src/IrisApiProject/database (from $GOPATH)
main.go:7:2: cannot find package "IrisApiProject/middleware" in any of:
	/usr/local/go/src/IrisApiProject/middleware (from $GOROOT)
	/Users/unitexiaowei/goProjects/src/IrisApiProject/middleware (from $GOPATH)
main.go:8:2: cannot find package "IrisApiProject/models" in any of:
	/usr/local/go/src/IrisApiProject/models (from $GOROOT)
	/Users/unitexiaowei/goProjects/src/IrisApiProject/models (from $GOPATH)`
这些不是网上开源的包的话,怎么引入进gopath

**Comment by snowlyg** [comment]
@uniteweiwei 你的这个是没有设置 GOPATH GOROOT 等环境变量。go env 看一下
