### ISSUE TITLE
exec: "gcc": executable file not found in %PATH%

### ISSUE THREAD

**Issue by kakj-go** [snowlyg/IrisAdminApi#6]
我本地下载了tdm-gcc,    
如图命令行也能用gcc.exe的命令   
![image](https://user-images.githubusercontent.com/28723047/58543077-47bba900-8231-11e9-9125-570b9090466d.png)为啥项目启动还是报标题的错误啊
错误如下   
```
# github.com/mattn/go-sqlite3
exec: "gcc": executable file not found in %PATH%
```

**Comment by 2357431193** [comment]
我用mysql跑起来了

**Comment by snowlyg** [comment]
sqlite3 是测试时候用的，运行用的mysql
